# Server/world_data.py

"""
This file contains static descriptions for Sims 4 Worlds and Neighborhoods (Open Streets).
IDs are obtained via the 'ai_loc_info' console command in-game.
"""

# --- NEIGHBORHOODS (Open Street IDs) ---
# Specific districts within a world (e.g., "Bedrock Strait" in Oasis Springs)
NEIGHBORHOOD_DESCRIPTIONS = {
    # San Myshuno
    1456220773: "Spice Market: A low-income neighborhood featuring the Spice Festival and Flea Market. It has three apartments, a community lot, and the Waterside Warble karaoke bar. People can enjoy basketball, food, festivals, performing guitar or violin on the center stage, and fishing at the waterside.",
    1788497979: "Myshuno Meadows: Surrounded by both trees and the cityscape, Myshuno Meadows is a great place for a relaxed wedding or outdoor birthday party.",
    1075237116: "Arts Quarter: Home to the Humor and Hijinks Festival, the bohemian Arts Quarter is beloved by musicians, artists and all manner of creative types.",
    4034911840: "Fashion District: Popular with trendy young crowd, hosts the Romance Festival and GeekCon. It's inspired by modern Asian cities like Tokyo and Shanghai.",
    3428213867: "Uptown: The luxurious heart of the City, this district is the domain of the rich, the powerful... and the slightly eccentric. Sims here can dine out, deliver speeches in the Uptown Civic Plaza, or frequent establishments like Skye Fitness and the Stargazer Lounge.",
    # Sulani
    1549761885: "Mua Pel'am: Nature dominates this remote Sulani island. Explore its beauty, from the active volcano and flowing waterfall to the secluded cave.",
    1893347376: "Ohan'ali Town: Ohan'ali is Sulani's main, most populated town. It features The Sand Bar, a popular spot for parties and traditions, as well as a beach. Once a small fishing camp, folks can still use a designated fishing spot here.",
    3105469928: "Lani St. Taz: It is an idyllic paradise which is known for its lush jungle environment which is ideal for exploring and white, sandy beaches with clear, calm water.",
    # Ravenwood
    416627306: "Whispering Glen: A quiet, rural haven in Ravenwood's countryside, offers a slow-paced life away from the local hauntings. Rich in ruins and rumors, it's ideal for collectors and historians. Explore the local Crypt, the Tarot Tome Shrine at the ruins' base, use community garden plots, or complete collections. A nightly festival takes place by the Ancestor face cliff.",
    369297339: "Mourningvale: An eerie, otherworldly place, home to many Ghosts and occasionally the Grim Reaper. The howls, moss-draped trees, odd Bell Tower clangs, and sentient plants contribute to its atmosphere. Sims can explore the Baleful Bog, the Tarot Tome Shrine, and the Guardian Tree (Alice). The town hosts the Afterlife Anonymous and Thinned Festivals.",
    2208554671: "Crow's Crossing: A village founded by Moppy the Goat, is known for regular hauntings and ghosts. Key locations include the Mysterious Merchant in the Specter graveyard, the Tarot Tome Shrine, an abandoned house, and the Well of Longing and Regret. Beware of Edith! Festivals hosted are the Try Before You Die Casket Sale, Crow's Crossing Celebration of Life, and Ravenwood Family Day.",
    # Windenburg
    3691563516: "Olde Platz: What Olde Platz lacks in greenery it makes up for in charming cobblestone. Live, work and play in the rich, cultural history of the oldest part of Windenburg.",
    1267499153: "Lykke Centre: Fresh, new, and arrestingly shiny, Lykke Centre is where new commerical enterprise in Windenburg thrives.",
    3398743073: "Windslar: Wide open spaces and a chateau or two. Visit or live in Windslar for a delectable taste of countryside living.",
    1084260742: "The Crumbling Isle: The Crumbling Isle, an exclusive, private neighborhood in Windenburg, is an island next to The Bluffs. It features high-end homes amidst cliffs and ancient ruins, with no roads.",
    1469628631: "The Island Bluff: The Bluff boasts a large bonfire area and a rustic, natural swimming pool that blends perfectly with the surrounding ocean. This makes it a popular spot for nighttime parties, with amenities including a WooHoo/sleep bush. Additionally, Sims visiting this scenic location might occasionally catch sight of a sea monster.",
    3982447363: "Ancient Ruins: Windenburg's prized ancient ruins bespeak a silent whisper of the civilization who lived here long ago. Enjoy walking paths through the historical architecture in the afternoon sun... or joining your friends for the occasional secret party.",
    2475261189: "Von Haunt Estate: The historic estate is a famous museum and tourist attraction, known for its enormous, perfectly pruned maze where Sims can get lost. The property is also inhabited by the ghosts of Mimsy and Bernard, the former owners, along with other random ghosts.",
    # Tartosa
    493539179: "Terra Amorosa: A short trip up the coastline from Porto Luminosos is the loving land known as Terra Amorosa to the locals. Whether fishing off the boardwalk, swimming at the bottom of the secluded Hideaway Falls, or hiking up the hillside to visit the area's famous Lover's Tree, any Sim is bound to fall madly in love with the various charming sights and historic landmarks this lover's paradise has to offer.",
    3442073656: "Porto Luminoso: Historians say Porto Luminoso's name originated when pirates arrived at shore, attracted by the glowing tides, the promise of trade, and the invention of the fruit tart. Overtime, the village flourished, and while still famous for its fruit tarts, Porto Luminoso's real claim to fame is its self-proclaimed-title as the wedding industry's premiere destination for romance and matrimonial services.",
    # Willow Creek
    1902162923: "Foundry Cove: Located in southern Willow Creek, Foundry Cove has lots of character (and its share of characters). Residents enjoy modest homes with a canal nearby for fishing, and a charming, active railroad.",
    2363457107: "Courtyard Lane: Courtyard Lane offers affordable homes for the upwardly mobile set. Classic styling mingles with larger shotguns and more expansive homes.",
    2280805822: "Pendula View: Pendula View is an affluent neighborhood in northern Willow Creek. It features large homes, manicured lawns, and a private community park.",
    2474553381: "Sage Estates: Willow Creek's most desirable area, Sage Estates features large, sprawling estates, lush landscaping, and the best high society has to offer.",
    2740343228: "Crawdad Quarter: Crawdad Quarter is the heart of Willow Creek. All of the towns liveliness, from parks to nightlife, can be found in this neighborhood.",
    1232026046: "Magnolia Blossom Park: Located in central Willow Creek, this park is ideal for socializing, skill-building, hobbies, and dates. Collectors will enjoy the numerous rocks, plants, and logs. Anglers can fish at the stream's shoreline or the small pond, where rare fish can be caught. The park offers monkey bars, a playset for children, and tables for chess. Restrooms are available in the small building at the back. A picnic area and good fishing spots are also found along the peninsula walkways.",
    # Oasis Springs
    617967630: "Bedrock Strait: A working-class neighborhood. New households to Oasis Springs usually settle here first because the properties are less expensive here compared to other neighborhoods. Residents of this delightfully kitschy neighborhood take pride in their billboards and lawn gnomes.",
    711065386: "Parched Prospect: This neighborhood is your quintessiential desert-living experience with bustling tumbleweeds and cacti as far as the eye can see!",
    3632553424: "Skyward Palms: This upscale gated community offers its residents all the warm, wild benefits of living in the desert along with the luxury of endless green grass. It features two lakes, which have two fishing spots each. In the center of the neighborhood, a water fountain and bench seats can be found bordered by roads.",
    1185542770: "Acquisition Butte: Residents of Acquisition Butte are paying premium for the gorgeous, rocky overlook and the sweet sound of solitude. A single strip of land where plants can be harvested and an abandoned mine can be found, being one of the ways into the Forgotten Grotto, the secret lot of the neighborhood.",
    1111996224: "Mirage Canyon: Oasis Spring's true oasis. Parched visitors passing through can always delight in seeing the gorgeous rushing waterfall and a well-appreciated pitstop. The surrounding area of Mirage Canyon features a number of fishing spots, a pirate-themed playscape and monkey bars, a fountain, a bunch of tables and chairs, barbecue grills.",
    2842140217: "Desert Bloom Park: Around the main park, there are paths and wilderness that visitors can explore. The neighborhood is in the center of Oasis Springs. It contains many barbecue grills and tables, a space-themed playscape and monkey bars, some chess tables, a fishing pond, an indoor lounge with a bar and public bathrooms. The surrounding areas feature three fishing spots, a few grills, tables and bench seats, public bathrooms.",
    # Newcrest
    3942535330: "Bridgeview: This family-friendly neighborhood has a lovely picnic area and a striking city skyline backdrop. There is a park near Fern Park with monkey bars, picnic tables and food stalls. Over by the canal is a small fishing pond.",
    3942535331: "Llama Lagoon: With lakeside walkways and public playground equipment, this neighborhood's just the right amount of cosmopolitan.",
    3942535328: "Ridgeline Drive: This busy strip of real estate lining the streets of the Newcrest suburbs boasts ample hiking trails.",
    # Magnolia Promenade has no neighborhoods
    # Forgotten Hollow has no neighborhoods
    # Brindleton Bay
    3864949102: "Sable Square: It is a quite large and open neighborhood. Close to the middle of the neighborhood is the grand monument, built by the residents of Brindleton Bay, dedicated to their cats and dogs. Next to the monument plaza is a small lake with a fishing spot, that then continues as a river up to the ocean. Sims can follow the small river, until they meet up with a small island, located between the separating river. The island includes two picnic tables and a trash can.",
    2893613071: "Whiskerman's Wharf: It is located on the waterfront, hosting a big pier full of food stalls, picnic tables and various fishing spots, along with boxes and other high areas where cats can jump up to. A special boat is also located in the pier, that Sims can use as a quick access to Deadgrass Isle. A pirate jungle gym for children is also located near the main pier.",
    1906928472: "Cavalier Cove: Known for its hiking trails and sprawling coastal properties, Cavalier Cove is the perfect place to go exploring or chase seagulls with an adventurous pup!",
    1685642028: "Deadgrass Isle: A mysterious shipwreck crashed on to Deadgrass Isle's shore and sunk in to the waves. The only survivors of the wreck was a lifeboat full of cats and dogs, causing Brindleton Bay to be full of pets, as it is today. The island has then been haunted by the ghost Captain Whitaker, along with other various deceased pets.",
    # Del Sol Valley
    2323227531: "Mirage Park: With reasonably priced homes and so close to downtown. Mirage Park is the perfect place for an up and coming star to start their rise to fame. The entire neighborhood consists of a small dead-end road. At the end of the road is a medium-sized playground with monkey bars, a Starcruiser X Jungle Gym, benches, barbecue grills, garbage bins, and public toilets",
    1420552844: "The Pinnacles: Fit for the rich and famous, The Pinnacles boast the most expensive homes in all of Del Sol Valley.",
    3882972916: "Starlight Boulevard: When it comes to night life Starlight Boulevard can not be beat. Where only the most famous Sims have access to the most exclusive night club in town. It is where the who's who of the industry come to show off.",
    # StrangerVille
    3934213596: "Shady Acres: Pristine, secluded, and nestled high atop a plateau, Shady Acres is home to the more wealthy locals of StrangerVille. Curious how some of them came into their wealth?",
    2018586480: "StrangerVille Plaza: This is where the locals like to hang out. You can find Scientists at the Library, Military Personnel at the Bar, and The Curio Shop near the park. You can buy some strange odds and ends here and find all the information you need.",
    # Glimmerbrook
    100140133: "Glimmerbrook Village: It has a very quiet, isolated, and, at times, \"conflicting\" feel, blending a secluded, natural, woodland look with somewhat more suburban-styled houses.",
    #Britechester
    12452862: "University of Britechester: The University of Britechester is based on English university architecture as well as the town it's in. The University features mostly university housing.\nThe University of Britechester distinguishes in the following degrees: Art History, Communications, Culinary Arts, Drama, Fine Art, History, and Language & Literature.\n\nThis university is the oldest in Britechester, founded by the famous Felix Psyded, who was well known for his enthusiasm for learning and humorously large books. As the years have passed the University of Britechester has established itself as an esteemed institute of classical education.",
    1465961617: "Foxbury Institute: It is said to be the \"premier place of higher learning\" with modern campus and facilities. Foxbury Institute is more Americanized compared to the other neighborhoods with the surrounding suburban houses. Foxbury Institute distinguishes the following degrees: Biology, Computer Science, Economics, Physics, Psychology, and Villainy. Foxbury Institute may seem young compared to the historical town surrounding it, but it has quickly distinguished itself in academia. For the students who have worked hard to attend Foxbury Institute, it's not just work, but the pursuit of personal passions that keeps this campus bustling.",
    2371324614: "Gibbs Hill: Gibbs Hill is nestled in the center of Britechester right between the two universities. Foxbury Institute and the University of Britechester. It was the first center of activity in Britechester and its famous Laurel Library has stayed a key location for many students to study and learn. The Pepper's Pub has also become a common spot for students from all around to make friends regardless of their rivalries.",
    # Evergreen Harbor
    2496862430: "Grims Quarry: When prospector Arnold Grims founded his famous rock quarry in Evergreen Harbor, he could hardly have predicted the little suburb that would spring up around it decades later. Today, a cozy set of homes, apartments, and spaces for community use sits in the shadow of the walls of striking white stone.",
    1821074231: "Conifer Station: What happens when the trains stop running? Downtown Evergreen, affectionately known to locals as Conifer Station, may be a bit quieter nowadays, but residents will tell you that the defunct train station and unsightly storage tanks hide a hard-working community eager to improve their little corner of the world.",
    369359163: "Port Promise: What was once a bustling trade port now holds a number of homes and businesses that pay homage to their industrial roots and aim to, as the local expression goes, \"Keep Evergreen Kooky!\" While the actual port may no longer be running, the promise of something better remains.",
    # Mt. Komorebi
    1491052508: "Wakaba: Like its namesake, Wakaba is young, new, and bright as the leaves of a tree in early springtime. This small town is up-and-coming in the region, home to beautiful, sleek new homes and an attractive town center featuring Mt. Komorebi's official mascot: Yamachan. Tourists of all ages can enjoy the Festival of Youth, or simply take in the neighborhood's natural beauty.",
    3002294565: "Senbamachi: The town of a thousand leaves, is the oldest in the region. Many locals enjoy the town's connection to nature, especially with the bamboo forests surrounding the town and unique spritely creatures that make a home in their leaves. It's said that if you walk the local trails long enough, you're bound to meet the guardians of the trees who reward those who love and respect their dwelling.",
    2458782193: "Yukimatsu: The true beauty of the countryside can be seen from Yukimatsu, named for its snow-covered pines. Located on the slopes of Mt. Komorebi, this area offers gorgeous vacation rentals, a variety of snow sports, untamed wilderness, and a peaceful Onsen Bathhouse getaway. Whether it's relaxation in a hot spring, seeing the sights of the Snow Festival, or an exhilarating climb to Mt. Komorebi's highest peak, this year-round snowy wonderland has something for everyone.",
    # Henford-on-Bagley
    2650041621: "Finchwick: Nestled along the River Bagley, the old mill village of Finchwick prides itself on its bustling and close-knit community. Its historic square features a pub and quaint stalls amid a flowering garden, perfect for a little window shopping. Tourists and locals alike flock to the weekly village fair, where Finchwick's Mayor makes a special appearance to judge entries and gossip about the latest happenings.",
    14190941: "Old New Henford: An area that boasts rolling hills, lush estates, and a small community garden, Old New Henford is perhaps best known for its historical naming woes. Initially known as Little Henford, the neighborhood renamed itself New Henford in an attempt to escape its diminutive origins. However, in neglecting to inform national mapmakers, they ceased to officially exist for a two-week period. When told that to be reinstated would require yet another name change, residents chose Old New Henford, which beat out the other choice 'New New Henford' by a single vote.",
    3913092862: "The Bramblewood: The natural beauty of these woods have long provided a picturesque place for many wild birds, rabbits, and foxes to call home. Whether secreting a small surprise under Sophie the Snail, bringing an easel to paint the serene Cordelia Falls, foraging for wild mushrooms, or finding romance among the ruins of the Isle of Volpe, any visitor would be transformed by a day in the Bramblewood.",
    # Moonwood Mill has no neighborhoods
    # Copperdale
    3741233432: "Rockridge Heights: Home to Copperdale High, Rockridge Heights is the town's standard-bearer for academia across generations. It's a beloved school ground for quintessential teen moments and college preparation. With classrooms full of learning, and an Auditorium full of Prom possibilities, Rockridge Heights is the perfect environment for every teen to discover who and what they want to be.",
    3013809927: "Prescott Square: Apart from the residentiallots, other spots of interest in this neighborhood include a gazebo with a bench, a lakeside boardwalk, a set of monkey bars in the park area, several scenic spots to sit and socialize or eat, and the infamous Boomsbluff Mystery House where a ghostly apparition of Jasper Prescott can briefly be seen on occasion during nighttime hours.",
    1505295608: "Plumbite Cove: Settled on Lake LaSuli sits Plumbite Cove, a once-popular location for its mining of rare gems. After the mines shut down, the town turned this picturesque outlook into a waterfront fairground. With thrills, chills, and a breathtaking view, Plumbite Pier is the ideal spot for all ages to make some memories. Travel to Totter Park to see the majestic Teeter Rock before heading to the pier to snag a selfie with the Frank the Flying Womp Womp tribute. Whether settling down or just stopping by, Plumbite Cove is a must-see Copperdale gem.",
    # San Sequoia
    3927353875: "Anchorpoint Wharf: Once the center of a bustling fishing and canning industry, Anchorpoint Wharf is known now as a vibrant area downtown featuring a movie theater, parklets, and more. There's plenty to keep all ages entertained.",
    2596862512: "Gilbert Gardens: Gilbert Gardens' gorgeous park was once owned by Gilbert Gilberts, a land developer who helped establish the area. Now, it's the perfect locale for family trips to the gardens. Where, amongst other activities, visitors can take a walk on one of the three scenic lake walking paths or visit the community's Splash Pad play area.",
    3962653297: "Hopewell Hills: Hopewell Hills is a cozy spot away from the hustle and bustle of town. The perfect place for anyone who wants, well, space! If the suburbs are your idea of paradise, you've found it here in this quiet neighborhood.",
    # Chestnut Ridge
    2808195162: "New Appaloosa: The historic New Appaloosa serves as a hub for Horse Riders, Ranchers, and Nectar Makers. Whether competing at the Hay Now! Equestrian Center, enjoying a night out at the dance hall, or savoring Nectar with good friends, this old watering hole has something for everyone.",
    657881596: "Riders' Glen: Watched over by the Trusty Steed Rock, known as \"Ol' Biscuit\" to the locals, Riders' Glen has been home to generations of Ranchers and Nectar Makers. With open space for Ranch Animals, ideal conditions for Nectar Making, and kind neighbors to boot. Riders' Glen is a welcome community for all walks of life.",
    525851134: "Galloping Gulch: Lauded as one of the go-to regions for Horse Riding, the Gulch is chockfull of gorgeous trails and stunning outlooks. Explore the Gulch's wonders as you honor the noble Horses that have passed on at Steed's Rest, explore the perilous Dreadhorse Caverns, or enjoy time under the stars at Saddle Summit Campgrounds",
    # Tomarang
    4017562985: "Morensong: A bustling neighborhood with pockets of idyllic peace and nooks of neighborly nuance! Morensong is the spot for vibrant communities to thrive, day or night. Stroll through the botanical garden or throw down in a game of playground hopscotch. Even join the Night Market buzz for some sunset shopping and moonlight munchies. The possibilities are endless!",
    934162359: "Koh Sahpa: It offers a more relaxed lifestyle along the river. After a dip in the sea or some much needed beach time, gather round at the Screaming Gecko for a drink or two. Feeling warm-hearted from all the sun? Visit the Sulea Tiger Sanctuary to support local conservation. No matter the choice, Koh Sahpa is the ideal spot for a go-with-the-flow attitude.",
    # Ciudad Enamorada
    271937272: "Nuevo Corazón: The pulsing nightlife of Ciudad Enamorada is the most exciting within Nuevo Corazón. This revitalized city area is where trendy partygoers head for a night on the town, scoping the room for the next potential love interest. Brave into the alluring and mysterious Mirador del Amor, the nightclub known as the hotspot for torrid affairs and passionate practitioners of the romantic arts. Not everyone enjoys the nightlife, though, so for you daytime daters, break a sweat and flex some muscles at the gym SUDOR.",
    1794983438: "Plaza Mariposa: It is the central square of Ciudad Enamorada, is the spot for scenic views and fun date night activities. Visit Media Naranja, the perfect park to stop at for a quick refreshment, or book a captivating getaway at the Villa Cálida rental. Excite your date with a romantic gift from Isabela's Flower Shop, or make a wish at the Fountain of Dreams.",
    2950084182: "Vista Hermosa: The serene embrace of Vista Hermosa sets the stage for a wide array of romantic experiences. Locals often visit Laguna del Abrazo, a bustling hot spot just a short walk from the renowned Wall of Love, where sweethearts can declare their love for each other. For those seeking a different type of connection, visit Beso Rápido, a conveniently located motel open 24/7.",
    # Nordhaven
    2518223919: "Gammelvik: Take a walk down the historic streets of Gammelvik and immerse yourself in the culture of Nordhaven's oldest district. Locals here like to take it slow, travel to work on their vintage bikes, and take long strolls by the old canals at night. Check out the central square for its Hobby Meetups and markets, or visit a lounge for a warm night of music.",
    3986516868: "Iverstad: Originally the industrial district of the city, Iverstad has recently turned into a natural settling spot for ambitious and stylist crowd. Many of its old factories have been repurposed as living spaces, and extensive terrains have recently been made available for new developments. Cross the bridge to the central island to check out its Hobby Meetups and meet the young community of this growing neighborhood. Just maybe steer clear of that one dark alley—they say a shady character hangs out there at night...",
    # Innisgreen
    1923335094: "Coast of Adhmor: A bustling seaside village filled with lore and history, the Coast of Adhmor serves as a tourist hotspot due to its colorful architecture, iconic landmarks, and coastal views.",
    2565964254: "Sprucederry Grove: It is a Haven for bohemian and nature-loving visitors who love gardening, living off the land, and mastering the Apothecary Skill. Nature enthusiasts flock here to forage among the picturesque trees and bathe in the tranquil stream. The neighbourhood takes its name from the local Legend, Spruce Almighty, the community's loving Garden Pal.",
    2565964254: "Everdew: Home of the Fairy Council, Everdew is the epicenter of Fairy life where Fairies can let it all hang out. Innisgreen's most enchanted neighborhood shimmers with a patina of magic all over its natural beauty.",


}

# --- WORLDS ---
# The broader map (e.g., Willow Creek, San Myshuno)
WORLD_DESCRIPTIONS = {
    1031066833949556757: "Willow Creek: Willow Creek offers a lush bayou of rolling hills and marshy riverways, known for its coastal hospitality, simple living, and long-standing reputations. It provides town comforts, lively neighbors, and diverse property options, making it an idyllic place to settle.",
    1031066833949921011: "Sulani: Sulani welcomes all to its gorgeous islands, featuring blue oceans and friendly neighbors. The main islands offer diverse lifestyles: the community-focused Ohan'ali Town, the upscale Lani St. Taz, and the vacant Mua Pel'am. Natural beauty is everywhere.",
    1031066833949707230: "San Myshuno: A bustling metropolis filled with skyscrapers, apartments, and cultural festivals.",
    1031066833950346870: "Ravenwood: It is a world known for its paranormal activity, ghostly powers, and numerous festivals.",
    1031066833949636126: "Windenburg: It comprises a countryside area in the mainland, an older styled quaint town center, a modern shore side and an island. Castle-like ruins can be found on the mainland and most of The Crumbling Isle is surrounded by crumbling man-made walls. These ruins are inspired by Gothic buildings in Europe (primarily Germany and Denmark) and they indicate the old age of the city.",
    1031066833950132828: "Tartosa: Mediterranean-inspired coastal world. It is characterized by beaches, waterfalls, a love-themed park, and a rustic, scenic landscape ideal for weddings, with a unique marriage registry office and, often, a lighthouse.",
    1031066833949561669: "Oasis Springs: An oasis nestled in the austere beauty of the western desert, this haven of eclectic culture is fringed by countless soaring palms, and lent vibrant color through impossibly lush landscaping. Oasis Springs offers relaxing retreats from the sun to any traveler who discovers it.",
    1031066833949636110: "Newcrest: Newcrest does not contain any pre-built lots. There are visible houses and high-rises.",
    1031066833949634933: "Magnolia Promenade: A world in which beautiful scenery meets metropolitan life! Magnolia Promenade offers fantastic views and a top of the line shopping experience for customers and entrepreneurs alike. Keep the kids entertained with a small playground and a small outdoor eating area. Enjoy a quiet outdoor seating area by the river where the ducks like to play.",
    1031066833949713059: "Forgotten Hollow: The small town of Forgotten Hollow has remained virtually unchanged for the four generations it has existed. All of its original town founders disappeared shortly after the town was founded. All except for Vladislaus Straud. His great grandson, Vladislaus Straud the IV, still watches over the town to this day. The sun rises later and sets earlier here, meaning you can enjoy more hours of darkness. Tour relics of founders and meet residents that have \"lived\" here for generations. Rare plants like Plasmafruit and the Sixam Mosquito Trap can only be found here",
    1031066833949779573: "Brindleton Bay: Discover the coastal shores of Brindleton Bay, a new world where inhabitants and their pets can live and enjoy outdoor activities. Play fetch near the harbor docks, take a walk to the lighthouse, or visit a park to setup an obstacle course.",
    1031066833949784595: "Del Sol Valley: Join the glitz and glamour of Del Sol Valley, a new world where you discover fame. Get a starter home in Mirage Park or work your way up to a house in the hills in The Pinnacles. Stroll the Boulevard and spot tiles of stars like Brytani Cho and Dirk Dreamer! Del Sol Valley is the prime location for a chance at meeting a Proper Celebrity!",
    1031066833949853569: "StrangerVille: It is a small town located on a red-sand desert plateau. The world hides a strange secret: its inhabitants behave strangely at night and there are plenty of scientists and military personnel walking around town.",
    1031066833949990396: "Glimmerbrook: It is a secluded, rustic, and mountainous, forested world designed with a mystical, fairy-tale, or \"cozy\" atmosphere. It is characterized by its alpine, Central European-style, small-town setting, featuring rocky terrain, a sparkling river, and a waterfall.",
    1031066833949922306: "Britechester: Begin a new chapter in the historical University of Britechester or modern Foxbury Institute. Live in a dorm room or off-campus in the welcoming town of Gibbs Hill. Explore Britechester on a bicycle, spend time in the student commons, and have a study session at the library. Cheer on the student body at a school spirit event and wear school colors to show your pride.",
    1031066833950056967: "Evergreen Harbor: It is an industrial, Pacific Northwest-inspired world focused on environmental impact and community development. It consists of three distinct neighborhoods—Port Promise, Grims Quarry, and Conifer Station—where players can transform polluted, industrial areas into green, sustainable, and thriving communities.",
    1031066833950060680: "Mt. Komorebi: It is a Japanese-inspired, winter-themed world. It is characterized by year-round snow in high-altitude areas, offering activities like skiing, snowboarding, rock climbing, and relaxing in hot springs. Locals have enjoyed the healing hot springs of Mt. Komorebi for centuries. Now, thanks to the modern snow sports resort in Yukimatsu, everyone else can, too! The region has become a hotspot for tourists looking for a vacation that's equal parts relaxing and adventurous.",
    1031066833950129218: "Henford-on-Bagley: It is a charming, English countryside-inspired world. It is famous for rolling hillsides, fresh farm produce and stonecarving which locals have been doing for hundreds of years.It is one of the first places Princess Cordelia visited after the Great Sloth Invasion.",
    1031066833950204265: "Moonwood Mill: Once upon a time, Moonwood Mill was filled with the bustle and sound of the nearby lumber mill. Today, the town is transformed. The rusted shells of its former industry provide cover for a handful of mysterious denizens who've sought out this wilderness-shrouded community, basking in its remote and anonymous nature. Surrounded by miles of wilderness and enriched by rare fauna and flora like the Luna Fish and Moonpetal Flower, Moonwood Mill is a nature-lover's paradise. The mysterious silhouettes lurking in the wilderness' trees are enough to make any visitor's fur - erm, hair - stand on end.",
    1031066833950201105: "Copperdale: Once renowned for its booming mining industry, the town of Copperdale, quaint and historic, lay nestled on the banks of Lake LaSuli. Founder Jasper Prescott had foraged this land for its treasured crystals, hoping Copperdale would one day blossom into a prosperous community for families and travellers alike. And though the mine carts reached an eternal halt, the townspeople continued to flourish. With academics and adventures abound, Copperdale is now home to many families seeking a small-town life with big-city dreams for themselves and their teens. Together they've unearthed a gem far more precious than before - beloved high school memories.",
    1031066833950270775: "San Sequoia: It began as a small fishing town, then became a hub of the fishing and canning industry due to the influence of local fisherman-turned-entrepreneur, Bayani Robles. The Robles family is still very much entrenched in the area even as it has expanded over time thanks to Gilbert Gilberts. Today, San Sequoia is home to cozy streets, a beautiful park with gardens, and quiet suburban neighborhoods. It's the perfect place to raise a family!",
    1031066833950273469: "Chestnut Ridge: In this town resides an equestrian community that is known for its expertise in horse training and nectar making. All neighborhoods have open spaces and long roads perfect for horse riding. There are also many jumping hurdles and barrels located in public spaces. At the town center, there is a clothing store, grocery, and an equestrian center for horse competitions.",
    1031066833950342321: "Tomarang: Grown from the humble roots off the coast of Shih Sea, Tomarang is lively with local fare, community chaos, and legends of lore. Known for its tight-knit communities and sun-filled shared spaces, Tomarang is a lush landscape of possibilities. Come cozy up with nature or fish around for neighborly niceties and whim-simsical secrets. Whether you're flying solo or raising generations, the region offers a warm welcome to any multi-living lifestyle! Sul Sul De-Kah!",
    1031066833950343711: "Ciudad Enamorada: A city for the romantics, Ciudad Enamorada is well known for its ample opportunities for romantic getaways and scandalous trysts. Whether head over heels or still looking for love, this city provides passionate moments for each. An aspiring romantic can explore Vista Hermosa for the warm and welcoming suburban life, the lush and picturesque Plaza Mariposa for walking hand in hand at sunset, or the traditional meets modern Nuevo Corazón for those seeking the alluring temptation of the nightlife.",
    1031066833950417067: "Nordhaven: This northern coastal city is known for its thriving, independent local businesses and the enchanting beauty of its cold seasons. Take a walk through the historic views of Gammelvik with its cobbled streets, classic architecture, and picturesque canals. Or hop on the train to Iverstad and explore how the locals are reinventing the industrial city center. Whether you seek to make your business flourish or just want to practice your hobbies with a cozy community, you will always find an opportunity here.",
    1031066833950419859: "Innisgreen: The enchanting isle of Innisgreen is renowned for its natural beauty and vibrant communities. Visitors from afar are drawn to the idyllic Sprucederry Grove, where Foraging is abundant and life flourishes in harmony with nature. In the mystical forest of Everdew, the pursuit of Fairy life and relationships offers enchanted experiences. Adventure awaits at the Coast of Adhmor, where the isle's rich history and secrets unfold through its engaging residents and monuments. Innisgreen is celebrated for its development of the Apothecary skill, attracting Sims eager to pursue careers in Naturopathy and holistic practices.",

    # Add more as you discover them
}